---
- name: Provision Cloud Infrastructure (AWS)
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Launch new EC2 instance for microservice
      amazon.aws.ec2_instance:
        instance_type: 't3.medium'
        image_id: 'ami-0c55b159cbfafe1f0' # Amazon Linux 2 AMI
        region: 'us-west-2'
        key_name: 'your-key-name' # CHANGE THIS
        vpc_subnet_id: 'subnet-0123456789abcdef' # CHANGE THIS
        security_group: 'sg-webserver-access'
        tags:
          Name: 'microservice-app-01'
          Project: 'LA-County-Project'